# Generated by Django 4.2.5 on 2023-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено'), ('pending', 'Ожидание')], default='pending', max_length=10),
        ),
    ]
