# Generated by Django 4.2.5 on 2023-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userschats', '0005_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
