# Generated by Django 4.2.5 on 2023-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userschats', '0006_remove_message_is_read_chatroom_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_read',
            new_name='all_messages_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
